### ISSUE TITLE
Descriptions are allowed on references, even though they are invalid and not actually saved anywhere

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#199]
**To Reproduce**

- Create a reference in an object
- Try to set a description on the reference
- Notice that setting a description is allowed, but it's not actually persisted anywhere

I would expect:

- Description button is greyed out on references
- Clicking/mousing over description button displays a tool-tip explaining how descriptions must be set on the reference itself

Or, like in Next, the description button is simply not available for references.

![Screen Shot 2019-10-17 at 8 54 20 AM](https://user-images.githubusercontent.com/4060903/67033602-c2e80380-f0db-11e9-9736-d979bc09e369.png)

**Comment by pytlesk4** [comment]
@rossmcdonald You can't have descriptions in refs, you would put that in the ref.

**Comment by chris-miaskowski** [comment]
@P0lip the icon is grayed out but I can still click on in and set description.

![ref-description.gif](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/6fdc7dfb-7123-402e-91a5-ae29bcb6eda7)

**Comment by P0lip** [comment]
@chris-miaskowski uh, I fixed, but not sure whether JSE was updated in Studio. Taking a look now.

**Comment by StoplightDeb** [comment]
@P0lip - I'm still seeing the same thing @chris-miaskowski saw above - it's greyed out but you can click and enter a description.  the description persists if you click the description icon to close it and then click to open again. also persists if you click around on other files and then back to the $ref > description icon

**Comment by P0lip** [comment]
It's still not updated, sorry for making it as ready to test. :sweat_smile: 
Apparently tests fail and PR couldn't be merged

**Comment by StoplightDeb** [comment]
@P0lip At last!  It is great, greyed out description icon for refs, can't add description, grand!

**Comment by P0lip** [comment]
Finally :sweat_smile: 
I'm so glad the dependency nightmare is about to come to an end. :laughing:
