### ISSUE TITLE
Query parameters $ref UI does not work

### ISSUE THREAD

**Issue by nasht00** [stoplightio/studio#425]
**Describe the bug**
Editing a GET request, in the query params section. I create a new param, then I click on the ref icon to link it to an existing model. The auto-complete is empty, and even if I try to force it it doesn't let me save. In other places (body for example) it works fine.

**Expected behavior**
Just like in body, autocomplete when selecting "This Project".

**Screenshots**
<img width="1045" alt="Screen Shot 2020-05-17 at 17 11 35" src="https://user-images.githubusercontent.com/329834/82150820-e9cd0a80-9861-11ea-8523-f7f92ff3a011.png">

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.11.0 (1.11.0.22031)
 - OS: macOS

**Comment by philsturgeon** [comment]
@nasht00 hey Nathan, sorry for the delay getting back to you, between the wild times _and_ a big release to prepare we've missed a few bits, but this is a high priority bug and we'll fix it up.

**Comment by philsturgeon** [comment]
Give it a try, should be working now. Enjoy!

**Comment by nasht00** [comment]
It still doesn't work. The autocomplete still says "No results found".

Version 1.13.1 (1.13.1.46368)

**Comment by philsturgeon** [comment]
Ahh you’re using Studio Desktop not Studio Web? The issue wasn’t clear. 

Studio Web is currently rather ahead of Studio Desktop while we finalise a few items in V2. Some fixes will be backported into the v1.x branch with a v1.14 so that could help.

If you’re blocked please consider using Studio Web for now, and subscribe here for updates of releases!

@lottamus please correct me if I’m wrong on this.
